[nfs]
172.31.54.237 ansible_ssh_user='ec2-user'

[webservers]
172.31.63.100 ansible_ssh_user='ec2-user'
172.31.58.48 ansible_ssh_user='ec2-user'

[db]
172.31.58.38 ansible_ssh_user='ec2-user' 

[lb]
172.31.48.85 ansible_ssh_user='ubuntu'